# Builds one SQL file you can paste into Supabase SQL Editor (run once, top to bottom).
$root = Split-Path -Parent $PSScriptRoot
$out = Join-Path $root "supabase\ALL_MIGRATIONS_COMBINED.sql"
$migrations = Get-ChildItem (Join-Path $root "supabase\migrations\*.sql") | Sort-Object Name

$header = @"
-- U-Sports: combined migrations (generated by scripts/combine-migrations.ps1)
-- Run in Supabase SQL Editor on a NEW project, OR use: supabase db push
-- Do not run twice on the same database unless you know migrations are idempotent.

"@

$header | Set-Content $out -Encoding UTF8
foreach ($f in $migrations) {
  "`n-- ========== $($f.Name) ==========`n" | Add-Content $out -Encoding UTF8
  Get-Content $f.FullName -Raw | Add-Content $out -Encoding UTF8
}

"`n-- ========== seed.sql (optional) ==========`n" | Add-Content $out -Encoding UTF8
Get-Content (Join-Path $root "supabase\seed.sql") -Raw | Add-Content $out -Encoding UTF8

Write-Host "Wrote $out"
