-- Player game stats (per match, sport-specific JSONB)
CREATE TABLE player_game_stats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  match_id UUID NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  athlete_id UUID NOT NULL REFERENCES athletes(id) ON DELETE CASCADE,
  sport TEXT NOT NULL,
  stats JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(match_id, athlete_id)
);

-- Player season stats (aggregated, recalculated post-game)
CREATE TABLE player_season_stats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  athlete_id UUID NOT NULL REFERENCES athletes(id) ON DELETE CASCADE,
  season_id UUID NOT NULL REFERENCES seasons(id) ON DELETE CASCADE,
  sport TEXT NOT NULL,
  games_played INTEGER DEFAULT 0,
  stats JSONB NOT NULL DEFAULT '{}',
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(athlete_id, season_id)
);

-- Team season stats (aggregated)
CREATE TABLE team_season_stats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  season_id UUID NOT NULL REFERENCES seasons(id) ON DELETE CASCADE,
  wins INTEGER DEFAULT 0,
  losses INTEGER DEFAULT 0,
  stats JSONB NOT NULL DEFAULT '{}',
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(team_id, season_id)
);

-- Leaderboard visibility (organizer toggles per athlete per season)
CREATE TABLE leaderboard_visibility (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  athlete_id UUID NOT NULL REFERENCES athletes(id) ON DELETE CASCADE,
  season_id UUID NOT NULL REFERENCES seasons(id) ON DELETE CASCADE,
  is_visible BOOLEAN DEFAULT TRUE,
  UNIQUE(athlete_id, season_id)
);

-- Insights (generated by Edge Function post-game)
CREATE TYPE insight_type AS ENUM ('trending_up', 'trending_down', 'streak', 'milestone');

CREATE TABLE insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_type TEXT NOT NULL CHECK (entity_type IN ('player', 'team')),
  entity_id UUID NOT NULL,
  sport TEXT NOT NULL,
  insight_text TEXT NOT NULL,
  insight_type insight_type NOT NULL,
  data JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ
);

-- GIN indexes for JSONB stat queries
CREATE INDEX idx_player_game_stats_stats ON player_game_stats USING GIN (stats);
CREATE INDEX idx_player_season_stats_stats ON player_season_stats USING GIN (stats);
CREATE INDEX idx_team_season_stats_stats ON team_season_stats USING GIN (stats);
CREATE INDEX idx_insights_entity ON insights (entity_type, entity_id);

-- RLS
ALTER TABLE player_game_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE player_season_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_season_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE leaderboard_visibility ENABLE ROW LEVEL SECURITY;
ALTER TABLE insights ENABLE ROW LEVEL SECURITY;

-- Public read for season stats (leaderboards)
CREATE POLICY "player_game_stats_select_all" ON player_game_stats FOR SELECT USING (TRUE);
CREATE POLICY "player_game_stats_write_admin" ON player_game_stats FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('organizer', 'super_admin'))
);

CREATE POLICY "player_season_stats_select_all" ON player_season_stats FOR SELECT USING (TRUE);
CREATE POLICY "player_season_stats_write_admin" ON player_season_stats FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('organizer', 'super_admin'))
);

CREATE POLICY "team_season_stats_select_all" ON team_season_stats FOR SELECT USING (TRUE);
CREATE POLICY "team_season_stats_write_admin" ON team_season_stats FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('organizer', 'super_admin'))
);

CREATE POLICY "leaderboard_visibility_select_all" ON leaderboard_visibility FOR SELECT USING (TRUE);
CREATE POLICY "leaderboard_visibility_write_admin" ON leaderboard_visibility FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('organizer', 'super_admin'))
);

CREATE POLICY "insights_select_all" ON insights FOR SELECT USING (TRUE);
CREATE POLICY "insights_write_admin" ON insights FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('organizer', 'super_admin'))
);

-- Enable realtime on leaderboard updates
ALTER PUBLICATION supabase_realtime ADD TABLE player_season_stats;
